In [1]:
# Add Matrices
import numpy as np
m=int(input("Enter row size:"))
n=int(input("Enter column size:"))
a=np.ones((m,n))
b=np.ones((m,n))
print("Enter values into array 1:")
for i in range(m):
    for j in range(n):
        k=int(input())
        a[i][j]=k
print("Enter values into array 2:")
for i in range(m):
    for j in range(n):
        k=int(input())
        b[i][j]=k
print("sum of 2 arrays:")
print(np.add(a,b))


Enter row size:2
Enter column size:2
Enter values into array 1:
1
2
3
4
Enter values into array 2:
5
6
7
8
sum of 2 arrays:
[[ 6.  8.]
 [10. 12.]]


In [3]:
# Multiply Matrices
import numpy as np
m1=int(input("Enter row size for array 1:"))
n1=int(input("Enter column size for array 1:"))
m2=int(input("Enter row size for array 2:"))
n2=int(input("Enter column size for array 2:"))
a=np.ones((m1,n1))
b=np.ones((m2,n2))
if n1!=m2:
    print("Please make sure that column size of 1st array and row size of second array need to be equal to perform array multiplication")
else:
    print("Enter values into array 1:")
    for i in range(m1):
        for j in range(n1):
            k=int(input())
            a[i][j]=k
    print("Enter values into array 2:")
    for i in range(m2):
        for j in range(n2):
            k=int(input())
            b[i][j]=k
    print("Multiplication of 2 arrays:")
    print(np.dot(a,b))


Enter row size for array 1:1
Enter column size for array 1:2
Enter row size for array 2:2
Enter column size for array 2:1
Enter values into array 1:
1
2
Enter values into array 2:
3
4
Multiplication of 2 arrays:
[[11.]]


In [4]:
# Replace Punctuations
s=input()
res=''
n='@_!#$%^&*()<>?/\|}{~:'
for i in s:
    if i not in n :
        res+=i
print(res)


srav*(&^ya
sravya


In [5]:
# Sort Sentence
s=input("Enter a sentence:")
l=s.split(" ")
for i in range(len(l)):
    l[i]=''.join(sorted(l[i]))
res=' '.join(l)
print(res)


Enter a sentence:i am sravya
i am aarsvy


In [6]:
# Transpose of a matrix
import numpy as np
m=int(input("Enter row size:"))
n=int(input("Enter column size:"))
a=np.ones((m,n))
print("Enter values into array:")
for i in range(m):
    for j in range(n):
        k=int(input())
        a[i][j]=k
print("Before transpose:")
print(a)
b=np.ones((m,n))
for i in range(m):
    for j in range(n):
        b[i][j]=a[j][i]
print("After transpose:")
print(b)


Enter row size:2
Enter column size:2
Enter values into array:
1
2
3
4
Before transpose:
[[1. 2.]
 [3. 4.]]
After transpose:
[[1. 3.]
 [2. 4.]]
